# cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age
# sops updatekeys secrets/common.yaml

keys:
  - &admin_yubikey_01   age1yubikey1qg5t2cm6ud9mpwmrnpxsg6gc8jmk8a4nnajztucy6wk4yvpwudjx5aptxg4
  - &admin_yubikey_02   age1yubikey1q2puqsepwxlhrgs69glhk353tp4r2zjy8exk9ysd7zs66erhw5akj5d8yre
  - &admin_backup       age169ptetg5gzq64nsmrqqa8g9r558kjpklyw20mrc20uj4gxnjeqkq3qw7xl


  - &host_hal9000       age1d9vzxup9plyvfutr0r0nzj4cfh2qryup9726u82d02uwvfcam54shhnqgw
  - &host_microvac      age1k6z9r6aevvzfzx2cq8fgzxjp98szv0c2lnzkufsrrnayvwul95qqaj2usp
  - &host_mindgame      age1rfs04gzdyjhk6dkx3d7yp2fm0m8j262jtwz72mwwgqumjx4ug3dqdm2fe7
  - &host_multivac      age1nkr35fkqs42egvrrzu85v3kjjs7g4djjdww8nn84x2rs8gx84qkssefma9

  - &host_glados        age1zkaum0rk8pkw8q5e2ucaewu98dw9wztf33pvgqfrqj34x74553zs72trwk
  - &host_do_prod_01    age1awzyuh2hyy60znaz7rte48leqs0t60m5lmvldd7vhewh8csh5f7sa22awc

  - &host_eddie         age1rulj6zv46hj64rdke3ycv93jrfrm729czpvvuvavvwtqtlks0u5sza9z5j
  - &host_marvin        age1jnrnyc4cuv306slhvkud8ae5w4rsf56wczxld09twsav8dmq0anqmppay3

  - &host_installer     age19wwufex8w6xdlj0cneml3d60uq9lqsn3zewqp3gr8p6t9qrc64dqaf9tf4
  - &host_do-base-image age1lgl5009r56s2tlgayfwruzxls6y55dfx9030uvgqmlsjhp4fppvq6382eh

creation_rules:
  - path_regex: secrets/hosts/hal9000\.yaml$
    key_groups:
      - age:
          - *admin_yubikey_01
          - *admin_yubikey_02
          - *admin_backup
          - *host_hal9000

  - path_regex: secrets/hosts/microvac\.yaml$
    key_groups:
      - age:
          - *admin_yubikey_01
          - *admin_yubikey_02
          - *admin_backup
          - *host_microvac

  - path_regex: secrets/hosts/mindgame\.yaml$
    key_groups:
      - age:
          - *admin_yubikey_01
          - *admin_yubikey_02
          - *admin_backup
          - *host_mindgame

  - path_regex: secrets/hosts/multivac\.yaml$
    key_groups:
      - age:
          - *admin_yubikey_01
          - *admin_yubikey_02
          - *admin_backup
          - *host_multivac

  - path_regex: secrets/hosts/glados\.yaml$
    key_groups:
      - age:
          - *admin_yubikey_01
          - *admin_yubikey_02
          - *admin_backup
          - *host_glados

  - path_regex: secrets/hosts/do-prod-01\.yaml$
    key_groups:
      - age:
          - *admin_yubikey_01
          - *admin_yubikey_02
          - *admin_backup
          - *host_do_prod_01

  - path_regex: secrets/hosts/eddie\.yaml$
    key_groups:
      - age:
          - *admin_yubikey_01
          - *admin_yubikey_02
          - *admin_backup
          - *host_eddie

  - path_regex: secrets/hosts/marvin\.yaml$
    key_groups:
      - age:
          - *admin_yubikey_01
          - *admin_yubikey_02
          - *admin_backup
          - *host_marvin

  - path_regex: secrets/hosts/installer\.yaml$
    key_groups:
      - age:
          - *admin_yubikey_01
          - *admin_yubikey_02
          - *admin_backup
          - *host_installer

  - path_regex: secrets/hosts/do-base-image\.yaml$
    key_groups:
      - age:
          - *admin_yubikey_01
          - *admin_yubikey_02
          - *admin_backup
          - *host_do-base-image

  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *admin_yubikey_01
          - *admin_yubikey_02
          - *admin_backup

          - *host_hal9000
          - *host_microvac
          - *host_mindgame
          - *host_multivac

          - *host_glados
          - *host_do_prod_01

          - *host_eddie
          - *host_marvin
