[blueMap]
enabled = true
includeSharestones = true
includeUndiscoveredWaystones = false
includeWaystones = true

[client]
disableTextGlow = false

[compatibility]
dynmap = true
journeyMap = true
preferJourneyMapIntegrationMod = true

[general]
allowedVisibilities = [ "global" ]
defaultVisibility = "global"
restrictedWaystones = [ "player" ]
scrollUseTime = 32
warpPlateUseTime = 15
warpStoneUseTime = 32

[inventoryButton]
creativeInventoryButtonX = 88
creativeInventoryButtonY = 33
inventoryButton = ""
inventoryButtonX = 58
inventoryButtonY = 60

[teleports]
enableCooldowns = true
enableCosts = true
enableDurability = true
enableModifiers = true
entityDenyList = [ "minecraft:wither" ]
transportLeashed = "enabled"
transportPets = "disabled"
warpRequirements = [
    "[is_not_interdimensional] scaled_add_xp_cost(distance, 0.01)",
    "[is_interdimensional] add_xp_cost(27)",
    "[source_is_warp_plate] multiply_xp_cost(0)",
    "[source_is_warp_stone] add_durability_cost(80)",
    "[target_is_global] multiply_xp_cost(0)",
    "min_xp_cost(0)",
    "max_xp_cost(27)",
    "[source_is_inventory_button] add_cooldown(inventory_button, 300)"
]

[worldGen]
chunksBetweenWildWaystones = 25
nameGenerationMode = "preset_first"
nameGenerationPresets = [  ]
nameGenerationTemplate = "{MrPork}"
spawnInVillages = "regular"
wildWaystoneStyle = "biome"
wildWaystonesDimensionAllowList = [ "minecraft:the_nether", "minecraft:the_end", "minecraft:overworld" ]
wildWaystonesDimensionDenyList = [  ]
